### ISSUE TITLE
（linux）源码下载下来没看到怎么运行,不知道如何编译

### ISSUE THREAD

**Issue by 0400H** [h167297/serials#1]
缺少个详细点的readme,看不太懂...

**Comment by h167297** [comment]
更新了 README.md，可以看下。

**Comment by h167297** [comment]
@0400H 更新了 README.md，可以看下。如果想直接下载体验使用可以用这三个命令

sudo add-apt-repository ppa:h167297/hening 
sudo apt-get update 
sudo apt-get install serials 

装好后会在桌面生成图标，双击打开即可。

支持：ubuntu14.04，ubuntu15.04，ubuntu16.04,ubuntu16.10，ubuntu17.04, 
ubuntu17.10,
