### ISSUE TITLE
linux下打不开串口

### ISSUE THREAD

**Issue by cmheia** [h167297/serials#2]
原因是里面的脚本都是`CRLF`，手动改了修复（我用apt安装的）

**Comment by h167297** [comment]
多谢提醒，我去找个时间修改后上传吧，这对人来说很不友好。不是每个人都会花精力手动修复的

**Comment by h167297** [comment]
把脚本格式转换后上传了新的，现在apt上已经是新的了

**Comment by yulincoder** [comment]
依然打不开啊，能识别到但是打不开。我用apt安装的

**Comment by h167297** [comment]
> 依然打不开啊，能识别到但是打不开。我用apt安装的
是不是用的虚拟机啊，没在虚拟机上试过

**Comment by h167297** [comment]
> 用
你看下，你的 /usr/sbin目录下的serialsdbus文件用vim打开是不是显示[dos]，这就是windows上的换行符格式。
用dos2unix serialsdbus 把格式转成Linux就行啦。
唉，由于发布的时候，在windows上动了脚本，手贱啊。
dos2unix命令不存在的话，就用sudo apt-get install dos2unix 命令下载安装下。

**Comment by h167297** [comment]
> > 依然打不开啊，能识别到但是打不开。我用apt安装的
> > 是不是用的虚拟机啊，没在虚拟机上试过

你看下，你的 /usr/sbin目录下的serialsdbus文件用vim打开是不是显示[dos]，这就是windows上的换行符格式。
用dos2unix serialsdbus 把格式转成Linux就行啦。
唉，由于发布的时候，在windows上动了脚本，手贱啊。
dos2unix命令不存在的话，就用sudo apt-get install dos2unix 命令下载安装下。

**Comment by h167297** [comment]
> 依然打不开啊，能识别到但是打不开。我用apt安装的
你看下，你的 /usr/sbin目录下的serialsdbus文件用vim打开是不是显示[dos]，这就是windows上的换行符格式。
用dos2unix serialsdbus 把格式转成Linux就行啦。
唉，由于发布的时候，在windows上动了脚本，手贱啊。
dos2unix命令不存在的话，就用sudo apt-get install dos2unix 命令下载安装下。

**Comment by h167297** [comment]
&nbsp; 你好，非常感谢你试用这个软件，你的问题应该是/usr/sbin/serialsdbus这个文件格式不对，需要dos2unix转换，文件格式导致的串口打不开问题，已经在下列系统中发布修复版本。你可以更新试试。

Trusty (14.04) ，Xenial (16.04)，Bionic (18.04)，Disco (19.04)，Eoan (19.10)，Focal (20.04)
初次安装：
sudo add-apt-repository ppa:h167297/hening
 sudo apt-get update
 sudo apt-get install serials

如果已经安装旧版，更新软件源

sudo apt-get update
最后安装
sudo apt-get install serials


卸载方式
sudo apt-get remove serials


附件中是18.04版本的离线安装包（deb）

自动判断 中文中文(简体)中文(香港)中文(繁体)英语日语朝鲜语德语法语俄语泰语南非语阿拉伯语阿塞拜疆语比利时语保加利亚语加泰隆语捷克语威尔士语丹麦语第维埃语希腊语世界语西班牙语爱沙尼亚语巴士克语法斯语芬兰语法罗语加里西亚语古吉拉特语希伯来语印地语克罗地亚语匈牙利语亚美尼亚语印度尼西亚语冰岛语意大利语格鲁吉亚语哈萨克语卡纳拉语孔卡尼语吉尔吉斯语立陶宛语拉脱维亚语毛利语马其顿语蒙古语马拉地语马来语马耳他语挪威语(伯克梅尔)荷兰语北梭托语旁遮普语波兰语葡萄牙语克丘亚语罗马尼亚语梵文北萨摩斯语斯洛伐克语斯洛文尼亚语阿尔巴尼亚语瑞典语斯瓦希里语叙利亚语泰米尔语泰卢固语塔加路语茨瓦纳语土耳其语宗加语鞑靼语乌克兰语乌都语乌兹别克语越南语班图语祖鲁语 自动选择 中文中文(简体)中文(香港)中文(繁体)英语日语朝鲜语德语法语俄语泰语南非语阿拉伯语阿塞拜疆语比利时语保加利亚语加泰隆语捷克语威尔士语丹麦语第维埃语希腊语世界语西班牙语爱沙尼亚语巴士克语法斯语芬兰语法罗语加里西亚语古吉拉特语希伯来语印地语克罗地亚语匈牙利语亚美尼亚语印度尼西亚语冰岛语意大利语格鲁吉亚语哈萨克语卡纳拉语孔卡尼语吉尔吉斯语立陶宛语拉脱维亚语毛利语马其顿语蒙古语马拉地语马来语马耳他语挪威语(伯克梅尔)荷兰语北梭托语旁遮普语波兰语葡萄牙语克丘亚语罗马尼亚语梵文北萨摩斯语斯洛伐克语斯洛文尼亚语阿尔巴尼亚语瑞典语斯瓦希里语叙利亚语泰米尔语泰卢固语塔加路语茨瓦纳语土耳其语宗加语鞑靼语乌克兰语乌都语乌兹别克语越南语班图语祖鲁语 有道翻译 百度翻译 谷歌翻译 谷歌翻译（国内） 翻译 朗读复制正在查询，请稍候……重试朗读复制复制朗读复制via 有道翻译译























 






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhangT"<notifications@github.com&gt;;
发送时间:&nbsp;2019年5月15日(星期三) 晚上6:05
收件人:&nbsp;"h167297/serials"<serials@noreply.github.com&gt;;
抄送:&nbsp;"1181839317"<h167297@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [h167297/serials] linux下打不开串口 (#2)




依然打不开啊，能识别到但是打不开。我用apt安装的
